# .github/workflows/hugo.yml
name: Hugo Actions

on:
  push:
    branches:
      - main  # 当 main 分析发生 push 时运行

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true  # 获取 Hugo 主题
          fetch-depth: 0    # 获取所有历史记录

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: '0.122.0'
          extended: false

      - name: Build Site
        run: |
          pwd
          ls
          cp -R exampleSite/* .
          hugo --themesDir ../ --baseURL https://xiaoanplus.github.io/so/

      - name: Deploy Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
          publish_branch: gh-pages
          force_orphan: true
          full_commit_message: ${{ github.event.head_commit.message }}
