# .github/workflows/hugo.yml
name: Hugo Actions

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: false
          fetch-depth: 0

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: '0.122.0'
          extended: false

      - name: Prepare site
        run: |
          # 复制 exampleSite 内容到根目录
          cp -R exampleSite/* .
          # 修改 config.toml 中的主题路径
          # sed -i 's|theme = "WebStack-Hugo"|theme = "layouts"|' config.toml

      - name: Build Site
        run: |
          hugo --baseURL https://xiaoanplus.github.io/so/

      - name: Deploy Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
          publish_branch: gh-pages
          force_orphan: true
          full_commit_message: ${{ github.event.head_commit.message }}
